### PR TITLE
Add Volume slider

### PR DESCRIPTION
**Pull request by woutdp**
I thought it would be nice to add a volume slider.

I'm not familiar with go so let me know if there's a convention issue or anything like that. 
Feel free to change any of this code and styling etc

This should close https://github.com/maxence-charriere/lofimusic/issues/4

image

### CODE REVIEW

**Comment by helloer** [comment]
Hah, I was also working on the same thing :D (I also used localStorage to store volume % so it doesn't reset after switching to another radio or page refresh). Maybe you can make use of it.

https://github.com/maxence-charriere/lofimusic/compare/master...helloer:feature/volume

**Comment by woutdp** [comment]
@helloer 
Oh, nice! I've pulled in your changes :)

(btw big fan of Soldat, played that game for a looong time some time ago)

**Comment by maxence-charriere** [comment]
Thanks for those. I was outside all of the day. Will take a look/update/merge tomorrow.

**Comment by woutdp** [comment]
Added a mute button:
image
image

**Review by maxence-charriere — COMMENTED** [review]
It looks good! Thank you for this! Gonna take this as basis and experiment with design :)

**Comment by maxence-charriere** [comment]
fix #3

**Pull request merged**
