### PR TITLE
#35: Update lofi girl youtube url

### PR DESCRIPTION
**Pull request by saeedafzal**
Update the url for Lofi Girl station to point to the new stream url.

#35

### CODE REVIEW

**Review by cco3 — APPROVED** [review]

**Comment by saeedafzal** [comment]
@maxence-charriere

**Comment by stuartskelton** [comment]
I was just about to suggest this MR, that URL points to the correct place for me

**Comment by stuartskelton** [comment]
@saeedafzal  can you also update the lofi sleepy girl url too, I think it should be https://youtu.be/rUxyKA_-grg

**Comment by saeedafzal** [comment]
> @saeedafzal can you also update the lofi sleepy girl url too, I think it should be https://youtu.be/rUxyKA_-grg

@stuartskelton I've updated the url for the lofi sleepy girl stream

**Comment by Dydnt** [comment]
It has been fixed.

**Pull request closed without merging**
